server:
  port: 9000
  address: 0.0.0.0

spring:
  application:
    name: tharvbytes-tasks
  security:
    oauth2:
      client:
        registration:
          icore:
            client-id: tharvbytes-task-app
            client-secret: "Tharvesh@2005."
            client-name: I.Core OIDC
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/icore"
            scope:
              - openid
              - profile
              - email
        provider:
          icore:
            issuer-uri: http://localhost:8080
            # Spring Security automatically retrieves the JWK Set, authorization,
            # token, and userinfo endpoints using OIDC Discovery via this issuer-uri.
