server:
  port: 8085

spring:
  application:
    name: web-ui
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: localhost
    port: 1025
    username: test
    password: test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
