spring.application.name=SpringSecurity

server.address=0.0.0.0
server.port = 80

spring.security.oauth2.client.registration.google.client-id=742087726024-f70t85l7tfjtcruo5ggagvc80nd9fke3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.github.client-id=Ov23liU7TpstQdlG8HPH
spring.security.oauth2.client.registration.github.client-secret=4c9665c330dc5bf5b09d580d2fa20f8cd6274eb9


spring.datasource.url=jdbc:h2:mem:springSecurity
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true