spring:
  application:
    name: my-drive-app

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: ${PORT:8000}

cloudinary:
  cloud-name: "dk6kgdu7u"
  api-key: "467544951485715"
  api-secret: "YMYzF36Pc6PoKiRh3DUNMycqyNg"
