package dev.tharbyte.MailSender.controller;

import dev.tharbyte.MailSender.service.SimpleMailService;
import jakarta.mail.MessagingException;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.time.LocalDateTime;

@RestController
public class MailController {

    @Autowired
    private SimpleMailService simpleService;
    private String content = String.format("""
        Hello,
        
        This is a dummy test email automatically generated by your Spring Boot application.
        
        Timestamp: %s
        Environment: Local/Development
        
        Best regards,
        Your App Build System
        """, LocalDateTime.now());


    @RequestMapping("/send-mail")
    public String textMail(){
        simpleService.sendSimpleMail(
                "tharveshmuhaideen@gmail.com",
                "imtharvesh@gmail.com",
                "[TEST] Spring Boot Application Notification",
                content
        );
        return "Success";
    }

    @RequestMapping("/send-mail-attachment")
    public String attachementMail() throws MessagingException {
        simpleService.sendAttachmentMail(
                "tharveshmuhaideen@gmail.com",
                "imtharvesh@gmail.com",
                "[TEST] Spring Boot Application Notification",
                content
        );
        return "Success";
    }

    String invite =  "/templates/mail-invite.html";
    String promotion =  "/templates/promotion-mail.html";
    String profile =  "/templates/mail-profile.html";

    @RequestMapping("/send-invite")
    public String inviteMail() throws MessagingException {
        try {

            simpleService.inviteMail(
                    "tharveshmuhaideen@gmail.com",
                    "imtharvesh@gmail.com",
                    "[TEST] Spring Boot Application | Invitation",
                    "mail-invite.html"
            );

            return "Email sent successfully.";

        } catch (MessagingException | IOException e) {
            return "Failed to send email: " + e.getMessage();
        }
    }

    @RequestMapping("/send-promote")
    public String promote() throws MessagingException {
        try {

            simpleService.inviteMail(
                    "tharveshmuhaideen@gmail.com",
                    "imtharvesh@gmail.com",
                    "[TEST] Spring Boot Application | Invitation",
                    "promotion-mail.html"
            );

            return "Email sent successfully.";

        } catch (MessagingException | IOException e) {
            return "Failed to send email: " + e.getMessage();
        }
    }

    @RequestMapping("/send-profile")
    public String profileMail() throws MessagingException {
        try {

            simpleService.inviteMail(
                    "tharveshmuhaideen@gmail.com",
                    "imtharvesh@gmail.com",
                    "[TEST] Spring Boot Application | Invitation",
                    "mail-profile.html"
            );

            return "Email sent successfully.";

        } catch (MessagingException | IOException e) {
            return "Failed to send email: " + e.getMessage();
        }
    }


}
